spring.application.name=jobfast

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobfast
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug HTTP client requests/responses
logging.level.com.lhpdesenvolvimentos.jobfast=DEBUG
logging.level.org.springframework.web.client=DEBUG

# CRON expression for the import job (runs daily at 3 AM)
job.import.cron=0 0 3 * * *
# job.import.cron=0 * * * * *

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lhpdesenvolvimentos@gmail.com
spring.mail.password=dbvxaoajqhihwtmy
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true

app.frontend.base-url=http://localhost:8080

# usar path/file (mais simples)
jwt.private-key-path=/Users/lucasprocopio/jwt_private.pem
jwt.public-key-path=/Users/lucasprocopio/jwt_public.pem
jwt.issuer=jobfast
jwt.access-token.expiration-minutes=15
jwt.refresh-token.expiration-days=30

# MAIL_MAILER=smtp
# MAIL_HOST=smtp.gmail.com
# MAIL_PORT=587
# MAIL_USERNAME="lhpdesenvolvimentos@gmail.com"
# MAIL_PASSWORD="dbvx aoaj qhih wtmy"
# MAIL_ENCRYPTION=tls
# MAIL_FROM_ADDRESS=no-reply@topcv.ia
# MAIL_FROM_NAME="${APP_NAME}"