spring.application.name=jobfast

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobfast
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debug HTTP client requests/responses
logging.level.com.lhpdesenvolvimentos.jobfast=DEBUG
logging.level.org.springframework.web.client=DEBUG

# CRON expression for the import job (runs daily at 3 AM)
job.import.cron=0 0 3 * * *
# job.import.cron=0 * * * * *

